name: Release

on:
    workflow_dispatch:
    release:
        types: [published]

permissions:
    id-token: write
    contents: read

env:
    TZ: ${{ vars.TZ }}
    FORCE_COLOR: 1

jobs:
    validate:
        name: Validate
        uses: ./.github/workflows/validate.yml
        secrets: inherit
